import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import {
  Inter,
  Noto_Serif_Georgian as Georgia,
  JetBrains_Mono,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Georgia({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "CareConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} min-h-full flex flex-col antialiased font-sans`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
